ResearchCollectionsAndPreservation/scsb-solr-client

src/main/java/org/recap/model/Bib.java
src/test/java/org/recap/executors/ExecutorTest.java

Added the fields that needs to be indexed.

Added the fields that needs to be indexed.

---

src/main/java/org/recap/executors/CoreAdminExecutorService.java
src/main/java/org/recap/executors/ItemIndexCallable.java
src/main/java/org/recap/model/Bib.java
src/main/java/org/recap/model/Item.java
src/main/java/org/recap/repository/main/ItemCrudRepository.java
src/main/java/org/recap/repository/temp/ItemCrudRepositoryMultiCoreSupport.java
src/test/java/org/recap/BaseTestCase.java
src/test/java/org/recap/BibIndexerTest.java
src/test/java/org/recap/ItemIndexerTest.java
src/test/java/org/recap/executors/ExecutorTest.java

Added Item pojo and indexed the item records.

Added Item pojo and indexed the item records.

---

src/main/java/org/recap/executors/IndexExecutorService.java
src/main/java/org/recap/executors/ItemIndexCallable.java
src/main/java/org/recap/executors/ItemIndexExecutorService.java
src/main/java/org/recap/model/Item.java
src/main/java/org/recap/util/ItemJSONUtil.java
src/test/java/org/recap/BaseTestCase.java
src/test/java/org/recap/ItemIndexerTest.java
src/test/java/org/recap/executors/ExecutorTest.java
src/test/java/org/recap/rest/service/ItemRESTIndexerTest.java

Added the Rest service for indexing the Item records.

Added the Rest service for indexing the Item records.

---

src/main/java/org/recap/util/ItemJSONUtil.java

Updated the availabilityStatus and collectionGroupDesignation to store code instead of id.

Updated the availabilityStatus and collectionGroupDesignation to store code instead of id.

---

src/main/java/org/recap/controller/SolrIndexController.java
src/main/java/org/recap/model/SolrIndexRequest.java
src/main/java/org/recap/model/SolrindexerRequest.java
src/main/resources/templates/solrIndexer.html

Added the solr indexing page using thymeleaf.

Added the solr indexing page using thymeleaf. 

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/controller/SolrIndexController.java
src/main/java/org/recap/executors/IndexExecutorService.java
src/main/resources/static/js/solrIndexer.js
src/main/resources/templates/solrIndexer.html

Wired SolrIndexerController with UI and added the auto refresh for status report

Wired SolrIndexerController with UI and added the auto refresh for status report

---

src/main/java/org/recap/util/BibJSONUtil.java
src/main/java/org/recap/util/ItemJSONUtil.java
src/test/java/org/recap/BibIndexerTest.java
src/test/java/org/recap/ItemIndexerTest.java

Removed setting the id manually.

Removed setting the id manually.

---

src/main/resources/application-dev.properties
src/main/resources/application.properties

Added logging properties

---

src/main/java/org/recap/model/jpa/BibliographicEntity.java
src/main/java/org/recap/model/jpa/BibliographicHoldingsEntity.java
src/main/java/org/recap/model/jpa/BibliographicItemEntity.java
src/main/java/org/recap/model/jpa/HoldingsEntity.java
src/main/java/org/recap/model/jpa/ItemEntity.java
src/main/java/org/recap/util/BibJSONUtil.java
src/main/java/org/recap/util/ItemJSONUtil.java

Updated the many to many mapping with composite primary key.

Updated the many to many mapping with composite primary key.

---

src/test/java/org/recap/rest/service/SolrFindMatchingRecordsTest.java

Added test for querying in the solr to find the matching records.

Added test for querying in the solr to find the matching records.

---

src/main/resources/application-local.properties

Added hibernate metrics properties

Added hibernate metrics properties

---

build.gradle

Added Cobertura plugin forn Jenkins Junit integration

Added Cobertura plugin forn Jenkins Junit integration

---

build.gradle
src/main/resources/application-junit.properties

Added property file for junit

---

src/main/resources/application-dev.properties
src/main/resources/application-junit.properties
src/main/resources/application-local.properties

Update the the rest url of scsb-persistence project

Update the the rest url of scsb-persistence project

---

src/test/java/org/recap/model/jpa/BibliographicEntityTest.java

Fixed findByOwningInstitutionIdAndOwningInstitutionBibId testcase

Fixed findByOwningInstitutionIdAndOwningInstitutionBibId testcase

---

src/main/java/org/recap/model/jpa/BibliographicEntity.java
src/main/java/org/recap/model/jpa/HoldingsEntity.java
src/main/java/org/recap/model/jpa/ItemEntity.java
src/test/java/org/recap/model/jpa/BibliographicEntityTest.java
src/test/java/org/recap/model/solr/SolrUnicodeTest.java

Fixed BibliographicEntityTest

---

src/main/java/org/recap/MatchingAlgorithm.java
src/main/java/org/recap/controller/MatchingAlgorithmController.java
src/main/java/org/recap/service/MatchingAlgorithmHelperService.java
src/main/resources/static/js/solrIndexer.js
src/main/resources/templates/solrIndexer.html
src/test/java/org/recap/rest/service/MatchingAlgorithmTest.java

Added UI and controller for generating MatchingAlgorithm Report.

Added UI and controller for generating MatchingAlgorithm Report.

---

src/test/java/org/recap/DiacriticalMarksUT.java
src/test/java/org/recap/admin/SolrAdminAT.java
src/test/java/org/recap/executors/ExecutorAT.java
src/test/java/org/recap/model/jpa/BibliographicEntityUT.java
src/test/java/org/recap/model/jpa/CollectionGroupEntityUT.java
src/test/java/org/recap/model/jpa/InstitutionEntityUT.java
src/test/java/org/recap/model/jpa/ItemStatusEntityUT.java
src/test/java/org/recap/model/solr/BibAT.java
src/test/java/org/recap/model/solr/ItemAT.java
src/test/java/org/recap/model/solr/SolrUnicodeAT.java
src/test/java/org/recap/repository/solr/main/BibSolrDocumentRepositoryAT.java
src/test/java/org/recap/rest/service/BibRESTIndexerAT.java
src/test/java/org/recap/rest/service/ItemRESTIndexerAT.java
src/test/java/org/recap/rest/service/MatchingAlgorithmAT.java
src/test/java/org/recap/util/MarcUtilUT.java

Renamed the test class name

---

src/main/resources/application-junit.properties

Updated the url configurations

Updated the url configurations

---

src/test/java/org/recap/model/jpa/BibliographicEntityUT.java
src/test/java/org/recap/model/solr/SolrUnicodeAT.java

Fixed issues in the testcases

---

src/test/java/org/recap/model/jpa/BibliographicEntityUT.java

Added character set while setting and fetching the records

Added character set while setting and fetching the records

---

src/main/java/org/recap/RecapConstants.java
src/test/java/org/recap/model/jpa/BibliographicEntityUT.java
src/test/java/org/recap/model/jpa/CollectionGroupEntityUT.java

Added asserts to method for coverage

Added asserts to method for coverage

---

src/main/resources/application-dev.properties

Update the url with the container name

Update the url with the container name

---

src/main/java/org/recap/model/solr/MatchingRecordReport.java
src/main/java/org/recap/service/MatchingAlgorithmHelperService.java
src/main/java/org/recap/util/CsvUtil.java

Added summary holdings in matching algorithm report.

Added summary holdings in matching algorithm report.

---

src/test/java/org/recap/executors/BibExecutorServiceUT.java
src/test/java/org/recap/model/search/BibDataFieldUT.java
src/test/java/org/recap/model/search/BibliographicMarcRecordUT.java
src/test/java/org/recap/model/search/SearchItemResultRowUT.java
src/test/java/org/recap/model/search/SearchRecordsRequestUT.java
src/test/java/org/recap/model/search/SearchResultRowUT.java

Added test cases for coverage

---

src/main/java/org/recap/model/solr/Bib.java
src/main/java/org/recap/model/solr/BibItem.java
src/main/java/org/recap/repository/solr/impl/BibSolrDocumentRepositoryImpl.java
src/main/java/org/recap/util/BibJSONUtil.java
src/test/java/org/recap/BaseTestCase.java
src/test/java/org/recap/model/solr/BibAT.java
src/test/java/org/recap/util/BibJSONUtilUT.java

Added startswith functionality for the search RECAP-103

Added startswith functionality for the search RECAP-103

---

src/main/java/org/recap/controller/SearchRecordsController.java
src/main/java/org/recap/model/search/SearchRecordsRequest.java
src/main/resources/templates/search.html

fixed the empty search issue and displayed a message.

fixed the empty search issue and displayed a message.

---

build.gradle

Added sonar.projectName property

Added sonar.projectName property

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/controller/MatchingAlgorithmController.java
src/main/java/org/recap/executors/MatchingAlgorithmCallable.java
src/main/java/org/recap/matchingAlgorithm/report/CSVMatchingAndExceptionReportGenerator.java
src/main/java/org/recap/matchingAlgorithm/report/FTPMatchingAndExceptionReportGenerator.java
src/main/java/org/recap/matchingAlgorithm/service/MatchingAlgorithmHelperService.java
src/main/java/org/recap/model/csv/MatchingReportReCAPCSVRecord.java
src/main/resources/static/js/solrIndexer.js
src/main/resources/templates/solrIndexer.html
src/test/java/org/recap/controller/MatchingAlgorithmControllerUT.java
src/test/java/org/recap/matchingAlgorithm/service/MatchingAlgorithmHelperServiceUT.java

Refactored the code and fixed the sorting and alignment issues during report generation.

Refactored the code and fixed the sorting and alignment issues during report generation.

---

src/main/resources/application-junit.properties

fixes for junit ftp keys folder

fixes for junit ftp keys folder

---

src/main/java/org/recap/model/search/resolver/impl/ISBNValueResolver.java
src/main/java/org/recap/model/search/resolver/impl/ISSNValueResolver.java
src/main/java/org/recap/model/search/resolver/impl/ImprintValueResolver.java
src/main/java/org/recap/model/search/resolver/impl/LccnValueResolver.java
src/main/java/org/recap/model/search/resolver/impl/LeaderMaterialTypeValueResolver.java
src/main/java/org/recap/model/search/resolver/impl/MaterialTypeValueResolver.java
src/main/java/org/recap/model/search/resolver/impl/NotesValueResolver.java
src/main/java/org/recap/model/search/resolver/impl/OCLCValueResolver.java
src/main/java/org/recap/model/search/resolver/impl/OwningInstitutionBibIdValueResolver.java
src/main/java/org/recap/model/search/resolver/impl/TitleSortValueResolver.java

Value resolver

---

src/main/java/org/recap/model/search/resolver/impl/item/CustomerCodeValueResolver.java
src/main/java/org/recap/model/search/resolver/impl/item/UseRestrictionValueResolver.java
src/main/java/org/recap/model/search/resolver/impl/item/VolumePartYearValueResolver.java

Added value resolver.

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/controller/swagger/SharedCollectionRestController.java
src/main/java/org/recap/model/accession/AccessionRequest.java
src/main/java/org/recap/repository/jpa/ItemDetailsRepository.java
src/main/java/org/recap/service/ItemAvailabilityService.java
src/main/resources/application-dev.properties
src/main/resources/application-junit.properties
src/main/resources/application-local-container.properties
src/main/resources/application-local.properties
src/main/resources/application-tst.properties
src/main/resources/application-uat.properties
src/test/java/org/recap/controller/swagger/SharedCollectionRestControllerUT.java
src/test/java/org/recap/repository/jpa/ItemDetailsRepositoryUT.java
src/test/resources/org/recap/controller/swagger/BibContent.xml
src/test/resources/org/recap/controller/swagger/HoldingsContent.xml

Added item availability status rest service

Added item availability status rest service

---

src/main/java/org/recap/repository/solr/impl/DataDumpSolrDocumentRepositoryImpl.java

Modified if condition to verify rootids

Modified if condition to verify rootids

---

src/main/resources/application-dev.properties
src/main/resources/application-junit.properties
src/main/resources/application-local-container.properties
src/main/resources/application-local.properties
src/main/resources/application-tst.properties
src/main/resources/application-uat.properties

Updated the report directory location

Updated the report directory location

---

src/main/java/org/recap/converter/MarcToBibEntityConverter.java
src/main/java/org/recap/service/accession/AccessionService.java
src/main/java/org/recap/util/AccessionSummaryRecordGenerator.java
src/test/java/org/recap/controller/AccessionSummaryReportUT.java

Added junit testcase for accession report and fixed one minor issue in accession report .

Added junit testcase for accession report and fixed one minor issue in accession report .

---

src/main/resources/templates/search.html
src/test/java/org/recap/controller/LoginControllerUT.java

Permission Update

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/camel/route/FSSubmitCollectionRejectionRouteBuilder.java
src/main/java/org/recap/camel/route/FTPSubmitCollectionRejectionRouteBuilder.java
src/main/java/org/recap/controller/GenerateReportController.java
src/main/java/org/recap/controller/SolrIndexController.java
src/main/java/org/recap/model/csv/SubmitCollectionRejectionRecord.java
src/main/java/org/recap/report/FSSubmitCollectionRejectionReportGenerator.java
src/main/java/org/recap/report/FTPSubmitCollectionRejectionReportGenerator.java
src/main/java/org/recap/report/ReportGenerator.java
src/main/java/org/recap/util/SubmitCollectionReportGenerator.java
src/main/resources/application-dev.properties
src/main/resources/application-junit.properties
src/main/resources/application-local-container.properties
src/main/resources/application-local.properties
src/main/resources/application-tst.properties
src/main/resources/application-uat.properties
src/main/resources/static/js/solrIndexer.js
src/main/resources/templates/solrIndexer.html

Submit collection changes

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/controller/CollectionController.java
src/main/java/org/recap/controller/CollectionUpdateController.java
src/main/java/org/recap/controller/LoginController.java
src/main/java/org/recap/controller/MarcRecordController.java
src/main/java/org/recap/controller/RequestController.java
src/main/java/org/recap/model/search/BibliographicMarcForm.java
src/main/java/org/recap/model/userManagement/UserDetailsForm.java
src/main/java/org/recap/security/UserManagement.java
src/main/java/org/recap/util/MarcRecordViewUtil.java
src/main/resources/templates/collection.html
src/main/resources/templates/login.html
src/main/resources/templates/searchRecords.html
src/test/java/org/recap/controller/CollectionControllerUT.java
src/test/java/org/recap/controller/CollectionUpdateControllerUT.java
src/test/java/org/recap/util/MarcRecordViewUtilUT.java

Request, CGD and Deaccession Permission Implementation

Request, CGD and Deaccession Permission Implementation

---

src/main/java/org/recap/controller/CollectionController.java
src/main/java/org/recap/controller/LoginController.java
src/main/java/org/recap/controller/MarcRecordController.java
src/main/java/org/recap/controller/ReportsController.java
src/main/java/org/recap/security/UserManagement.java
src/main/java/org/recap/util/MarcRecordViewUtil.java
src/main/resources/templates/searchRecords.html

Request , Deaccesion and CGD issue Fix

Request , Deaccesion and CGD issue Fix

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/model/jpa/BibliographicEntity.java
src/main/java/org/recap/model/jpa/ItemEntity.java
src/main/java/org/recap/service/accession/AccessionService.java
src/main/java/org/recap/service/partnerservice/PrincetonService.java
src/main/resources/org/recap/service/accession/dummybibcontent.xml
src/main/resources/org/recap/service/accession/dummyholdingcontent.xml
src/test/java/org/recap/service/accession/AccessionServiceUT.java

Accession changes

---

src/main/java/org/recap/service/accession/AccessionService.java

Accession changes -  get xml string content using getResourceAsStream()

Accession changes -  get xml string content using getResourceAsStream()

---

src/main/java/org/recap/repository/jpa/ItemChangeLogDetailsRepository.java
src/main/java/org/recap/util/ReportsUtil.java
src/test/java/org/recap/repository/jpa/ItemChangeLogDetailsRepositoryUT.java
src/test/java/org/recap/util/ReportsUtilUT.java

Fetching Deaccession Item Information

Fetching Deaccession Item Information 

---

src/main/java/org/recap/controller/ReportsController.java
src/main/java/org/recap/model/search/ReportsForm.java
src/main/java/org/recap/util/ReportsUtil.java
src/main/resources/static/js/report.js
src/main/resources/templates/reports.html
src/test/java/org/recap/controller/ReportsControllerUT.java
src/test/java/org/recap/util/ReportsUtilUT.java

Pagination For Deaccession Report - Recap 388

Pagination For Deaccession Report - Recap 388

---

src/main/java/org/recap/controller/UserRoleController.java
src/main/java/org/recap/model/jpa/RoleEntity.java
src/main/java/org/recap/model/userManagement/UserRoleForm.java
src/main/java/org/recap/model/userManagement/UserSearchResultRow.java
src/main/java/org/recap/repository/jpa/RolesDetailsRepositorty.java
src/main/java/org/recap/repository/jpa/UserDetailsRepository.java
src/main/java/org/recap/service/userManagement/UserRoleService.java
src/main/java/org/recap/service/userManagement/UserRoleServiceImpl.java
src/main/java/org/recap/service/userManagement/UserRoleValidator.java
src/main/resources/static/js/userRole.js
src/main/resources/templates/searchRecords.html
src/main/resources/templates/userRolesSearch.html

User & Role Initital Implementation - 06-01

User & Role Initital Implementation - 06-01

---

src/main/java/org/recap/controller/SolrIndexController.java
src/main/java/org/recap/service/accession/SolrIndexService.java
src/test/java/org/recap/service/accession/SolrIndexServiceUT.java

Submit collection changes - to update owning institution bib,holding and item id

Submit collection changes - to update owning institution bib,holding and item id

---

src/main/resources/static/js/bootstrap-add-clear.min.js
src/main/resources/static/js/search.js
src/main/resources/templates/search.html

Recap - 320 Clear Icon in search ui fixed

Recap - 320 Clear Icon in search ui fixed

---

src/main/resources/static/js/bootstrap-add-clear.min.js
src/main/resources/templates/search.html

Recap 320 clear X  icon

---

src/main/resources/application-dev.properties
src/main/resources/application-junit.properties
src/main/resources/application-local-container.properties
src/main/resources/application-tst.properties
src/main/resources/application-uat.properties

updated the jmx url

---

src/main/java/org/recap/repository/solr/impl/DataDumpSolrDocumentRepositoryImpl.java

Removed log statement

---

src/main/resources/application-local-container.properties

Updated the logging file path

---

src/main/java/org/recap/controller/MatchingAlgorithmController.java
src/main/java/org/recap/matchingAlgorithm/service/MatchingBibInfoDetailService.java
src/main/java/org/recap/model/jpa/MatchingBibInfoDetail.java
src/main/java/org/recap/repository/jpa/MatchingBibInfoDetailRepository.java
src/main/java/org/recap/repository/jpa/ReportDataDetailsRepository.java
src/main/java/org/recap/repository/jpa/ReportDetailRepository.java
src/main/resources/application-dev.properties
src/main/resources/application-junit.properties
src/main/resources/application-local-container.properties
src/main/resources/application-local.properties
src/main/resources/application-tst.properties
src/main/resources/application-uat.properties
src/main/resources/static/js/solrIndexer.js
src/main/resources/templates/solrIndexer.html
src/test/java/org/recap/matchingAlgorithm/service/MatchingBibInfoDetailServiceUT.java
src/test/java/org/recap/model/jpa/ReportDetailRepositoryUT.java
src/test/java/org/recap/repository/jpa/ReportDataDetailsRepositoryUT.java

Added logic to load matching bib info in a separate table

Added logic to load matching bib info in a separate table

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/controller/UpdateItemStatusController.java
src/main/java/org/recap/model/jpa/ItemEntity.java
src/main/java/org/recap/model/solr/Item.java
src/main/java/org/recap/repository/solr/impl/DataDumpSolrDocumentRepositoryImpl.java
src/main/java/org/recap/util/ItemJSONUtil.java
src/main/java/org/recap/util/SolrQueryBuilder.java
src/main/java/org/recap/util/UpdateCgdUtil.java
src/test/java/org/recap/repository/solr/impl/DataDumpSolrDocumentRepositoryImplAT.java
src/test/java/org/recap/util/SolrQueryBuilderUT.java
src/test/java/org/recap/util/UpdateCgdUtilUT.java

RECAP-394 - included items whose CGD was edited from 'Shared/Open' to 'Private' to the delete feed

RECAP-394 - included items whose CGD was edited from 'Shared/Open' to 'Private' to the delete feed

---

src/main/resources/application-junit.properties

updated the junit property

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/repository/solr/impl/DataDumpSolrDocumentRepositoryImpl.java
src/main/java/org/recap/util/SolrQueryBuilder.java

RECAP-412 - Exclude incomplete record in data dump

RECAP-412 - Exclude incomplete record in data dump

---

src/main/java/org/recap/util/ReportsServiceUtil.java

deaccession report pagination lastbutton problem fixed

deaccession report pagination lastbutton problem fixed

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/camel/route/FSOngoinAccessionReportRouteBuilder.java
src/main/java/org/recap/camel/route/FTPOngoingAccessionReportRouteBuilder.java
src/main/java/org/recap/controller/GenerateReportController.java
src/main/java/org/recap/controller/SharedCollectionRestController.java
src/main/java/org/recap/model/csv/OngoingAccessionReportRecord.java
src/main/java/org/recap/report/FSOngoingAccessionReportGenerator.java
src/main/java/org/recap/report/FTPOngoingAccessionReportGenerator.java
src/main/java/org/recap/report/ReportGenerator.java
src/main/java/org/recap/service/accession/AccessionService.java
src/main/java/org/recap/service/partnerservice/PrincetonService.java
src/main/java/org/recap/util/OngoingAccessionReportGenerator.java
src/main/resources/application-dev.properties
src/main/resources/application-junit.properties
src/main/resources/application-local-container.properties
src/main/resources/application-local.properties
src/main/resources/application-tst.properties
src/main/resources/application-uat.properties
src/main/resources/templates/solrIndexer.html
src/test/java/org/recap/controller/AccessionSummaryReportUT.java
src/test/java/org/recap/service/accession/AccessionServiceUT.java

RECAP-462 - Ability to process multiple barcode/customer code during Ongoing Accession

RECAP-462 - Ability to process multiple barcode/customer code during Ongoing Accession

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/controller/SharedCollectionRestController.java
src/main/resources/application-dev.properties
src/main/resources/application-junit.properties
src/main/resources/application-local-container.properties
src/main/resources/application-local.properties
src/main/resources/application-tst.properties
src/main/resources/application-uat.properties

Added input limit to accession service

Added input limit to accession service

---

src/test/java/org/recap/controller/swagger/SharedCollectionRestControllerUT.java

Removed unwanted import statements

Removed unwanted import statements

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/controller/SharedCollectionRestController.java
src/main/java/org/recap/service/accession/AccessionService.java
src/test/java/org/recap/service/accession/AccessionServiceUT.java

RECAP-488 - Added appropriate response message for Accession

RECAP-488 - Added appropriate response message for Accession

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/repository/jpa/ItemDetailsRepository.java
src/main/java/org/recap/service/accession/AccessionService.java
src/test/java/org/recap/repository/jpa/ItemDetailsRepositoryUT.java

RECAP-433 - Throw error message while accession if the barcode is already exist in SCSB

RECAP-433 - Throw error message while accession if the barcode is already exist in SCSB

---

src/main/java/org/recap/executors/MatchingAlgorithmCGDCallable.java
src/main/java/org/recap/matchingAlgorithm/MatchingAlgorithmCGDProcessor.java
src/main/java/org/recap/matchingAlgorithm/service/MatchingAlgorithmUpdateCGDService.java
src/main/java/org/recap/service/accession/AccessionService.java
src/main/java/org/recap/util/OngoingMatchingAlgorithmUtil.java

Fixed the issue with boundwith records in the ongoing matching algorithm.

Fixed the issue with boundwith records in the ongoing matching algorithm.

---

src/main/java/org/recap/service/accession/AccessionService.java

RECAP-466 - Fixed one bib multiple item during accession

RECAP-466 - Fixed one bib multiple item during accession

---

src/main/java/org/recap/controller/GenerateReportController.java
src/main/java/org/recap/controller/MatchingAlgorithmController.java
src/main/java/org/recap/model/solr/SolrIndexRequest.java
src/main/resources/static/js/solrIndexer.js
src/main/resources/templates/solrIndexer.html

Recap 497 Added To Date in Generate Reports tab of Solr client project

Recap 497 Added To Date in Generate Reports tab of Solr client project

---

src/main/resources/application-dev.properties
src/main/resources/application-junit.properties
src/main/resources/application-local-container.properties
src/main/resources/application-local.properties
src/main/resources/application-tst.properties
src/main/resources/application-uat.properties

Updated the urls with the container name

Updated the urls with the container name

---

src/main/java/org/recap/repository/jpa/ItemDetailsRepository.java
src/main/java/org/recap/service/accession/AccessionService.java
src/test/java/org/recap/repository/jpa/ItemDetailsRepositoryUT.java
src/test/java/org/recap/service/accession/AccessionServiceUT.java

RECAP-524 - Fixed the issue for accessioning an item which is deaccessioned

RECAP-524 - Fixed the issue for accessioning an item which is deaccessioned

---

src/main/java/org/recap/RecapConstants.java

Recap-530 Modified RecapConstant terms

Recap-530 Modified RecapConstant terms

---

src/main/java/org/recap/controller/SharedCollectionRestController.java
src/main/java/org/recap/service/ItemAvailabilityService.java
src/test/java/org/recap/controller/swagger/SharedCollectionRestControllerUT.java

Recap-557  Item Availability Status Failed for Multiple search

Recap-557 fixed Item Availability Status Failed for Multiple search

---

src/main/java/org/recap/controller/ReportsRestController.java
src/main/java/org/recap/model/reports/ReportsRequest.java
src/main/java/org/recap/model/reports/ReportsResponse.java
src/main/java/org/recap/model/search/IncompleteReportResultsRow.java
src/main/java/org/recap/model/search/SearchRecordsRequest.java
src/main/java/org/recap/model/search/SearchResultRow.java
src/main/java/org/recap/repository/solr/impl/BibSolrDocumentRepositoryImpl.java
src/main/java/org/recap/util/ReportsServiceUtil.java
src/main/java/org/recap/util/SearchRecordsUtil.java

Recap-552 Incomplete Record Report For accession

Recap-552 Incomplete Record Report For accession

---

src/main/java/org/recap/util/BibJSONUtil.java

Recap-509 : Removed the sub tags $6,$8 from 24X and $0,$4,$6,$8 from 1XX .

Recap-509 : Removed the sub tags $6,$8 from 24X and $0,$4,$6,$8 from 1XX .

---

src/main/java/org/recap/model/search/SearchRecordsRequest.java
src/main/java/org/recap/repository/solr/impl/BibSolrDocumentRepositoryImpl.java
src/main/java/org/recap/util/ReportsServiceUtil.java

Recap-571 & 572 fixed Export Record Exports only Max of 10 Records to  CSV file and Incomplete' CUL Item not displayed in Reports After accession.

Recap-571 & 572 fixed Export Record Exports only Max of 10 Records to  CSV file and Incomplete' CUL Item not displayed in Reports After accession.

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/util/ReportsServiceUtil.java

Recap-571 Incomplete' CUL Item not displayed in Reports After accession

Recap-571 Incomplete' CUL Item not displayed in Reports After accession

---

src/test/java/org/recap/util/OngoingMatchingAlgorithmUtilUT.java

Fixed the test case for ongoing matching algorithm.

Fixed the test case for ongoing matching algorithm.

---

src/main/java/org/recap/service/accession/AccessionService.java

RECAP-592 - Change the CGD to "Not Available" for dummy records

RECAP-592 - Change the CGD to "Not Available" for dummy records

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/model/search/DeaccessionItemResultsRow.java
src/main/java/org/recap/repository/jpa/ItemChangeLogDetailsRepository.java
src/main/java/org/recap/util/ReportsServiceUtil.java
src/test/java/org/recap/repository/jpa/ItemChangeLogDetailsRepositoryUT.java

Recap-617 Deaccession report not working for Columbia.

Recap-617 Deaccession report not working for Columbia.

---

src/main/resources/application.properties

RECAP-703 :  Added application.properties.

RECAP-703 :  Added application.properties.

---

src/main/java/org/recap/admin/SolrAdmin.java
src/main/java/org/recap/camel/route/SolrRouteBuilder.java
src/main/java/org/recap/config/SwaggerConfig.java
src/main/java/org/recap/config/SwaggerInterceptor.java
src/main/java/org/recap/controller/SharedCollectionRestController.java
src/main/java/org/recap/controller/UpdateCgdRestController.java
src/main/java/org/recap/controller/UpdateItemStatusController.java
src/main/java/org/recap/controller/UpdateJobController.java
src/main/java/org/recap/controller/swagger/SearchRecordRestController.java
src/main/java/org/recap/converter/XmlToBibEntityConverterInterface.java
src/main/java/org/recap/model/csv/SolrExceptionReportReCAPCSVRecord.java
src/main/java/org/recap/model/csv/SubmitCollectionReportRecord.java
src/main/java/org/recap/model/csv/SummaryReportReCAPCSVRecord.java
src/main/java/org/recap/model/jaxb/marc/SubfieldatafieldType.java
src/main/java/org/recap/model/jpa/UsersEntity.java
src/main/java/org/recap/model/search/SearchRecordsRequest.java
src/main/java/org/recap/model/search/SearchRecordsResponse.java
src/main/java/org/recap/model/search/SearchResultRow.java
src/main/java/org/recap/model/search/resolver/ValueResolver.java
src/main/java/org/recap/model/solr/SolrIndexRequest.java
src/main/java/org/recap/model/usermanagement/UserDetailsForm.java
src/main/java/org/recap/repository/jpa/UserDetailsRepository.java
src/main/java/org/recap/service/accession/SolrIndexService.java
src/main/java/org/recap/util/SearchRecordsUtil.java
src/main/java/org/recap/util/SolrQueryBuilder.java
src/main/java/org/recap/util/SubmitCollectionReportGenerator.java
src/main/java/org/recap/util/UpdateCgdUtil.java

Javadocs for solr client project.

Javadocs for solr client project.

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/service/accession/AccessionService.java

Recap - 775 Added code to check the length of the barcode

Recap - 775 Added code to check the length of the barcode

---

src/main/java/org/recap/controller/SharedCollectionRestController.java
src/main/java/org/recap/model/accession/BatchAccessionResponse.java
src/main/java/org/recap/service/accession/AccessionService.java
src/main/java/org/recap/service/accession/BulkAccessionService.java
src/main/java/org/recap/service/accession/callable/BibDataCallable.java
src/main/java/org/recap/util/AccessionHelperUtil.java
src/main/resources/application.properties

RECAP-813 : Fixed the issue with batch acccession performance.

RECAP-813 : Fixed the issue with batch acccession performance.

---

src/main/java/org/recap/util/AccessionHelperUtil.java

RECAP-827 : Modified for Change Request - Barcode history in Acc/Deacc.

RECAP-827 : Modified for Change Request - Barcode history in Acc/Deacc.

---

src/main/java/org/recap/service/accession/AccessionService.java

…no holding id from bib data api - this happens for NYPL

Fixed accession issue for multiple item attached to same holding but no holding id from bib data api - this happens for NYPL

---

src/main/java/org/recap/config/SwaggerInterceptor.java
src/main/java/org/recap/spring/PropertyValueProvider.java
src/main/java/org/recap/spring/SwaggerAPIProvider.java
src/main/java/org/recap/util/AccessionHelperUtil.java
src/main/resources/application.properties
src/test/java/org/recap/controller/BaseControllerUT.java

Recap 867 - Removed Hard coded swagger api keys

Recap 867 - Removed Hard coded swagger api keys

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/report/FTPSubmitCollectionSummaryReportGenerator.java

Recap-800 Changed filename and email content for submit collection

Recap-800 Changed filename and email content for submit collection

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/controller/TransferController.java
src/main/java/org/recap/model/transfer/HoldingTransferResponse.java
src/main/java/org/recap/model/transfer/ItemTransferRequest.java
src/main/java/org/recap/model/transfer/ItemTransferResponse.java
src/main/java/org/recap/service/transfer/TransferService.java

Modified for RECAP-882, RECAP-890, RECAP-889, RECAP-883, RECAP-891 and RECAP-882

Modified for RECAP-882, RECAP-890, RECAP-889, RECAP-883, RECAP-891 and RECAP-882

---

src/main/java/org/recap/camel/route/EmailRouteBuilder.java
src/main/resources/application.properties

Recap 800 added cc for update cgd

Recap 800 added cc for update cgd

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/service/accession/AccessionService.java
src/main/java/org/recap/service/partnerservice/ColumbiaService.java
src/main/java/org/recap/service/partnerservice/NYPLService.java
src/main/java/org/recap/service/partnerservice/PrincetonService.java
src/main/java/org/recap/service/transfer/TransferService.java
src/main/java/org/recap/util/AccessionHelperUtil.java
src/main/java/org/recap/util/OngoingAccessionReportGenerator.java

Modified for  RECAP-883,  RECAP-903 and RECAP-900

Modified for  RECAP-883,  RECAP-903 and RECAP-900

---

src/main/java/org/recap/executors/BibItemIndexCallable.java
src/main/java/org/recap/executors/IndexExecutorService.java

Fixed bug to display logs

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/util/ReportsServiceUtil.java

Ms-12 Accession and Deaccession Count mismatch for PUL fixed.

Ms-12 Accession and Deaccession Count mismatch for PUL fixed.

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/service/transfer/TransferService.java

MS-115 - Deaccessioned item or holding cannot be tranferred through transfer api.

MS-115 - Deaccessioned item or holding cannot be tranferred through transfer api.

---

src/main/java/org/recap/RecapConstants.java
src/main/java/org/recap/util/OngoingMatchingAlgorithmUtil.java

ms-142 ongoing matching algorithm - title execption wont be shown if not processed

ms-142 ongoing matching algorithm - title execption wont be shown if not processed

---

src/main/java/org/recap/service/partnerservice/ColumbiaService.java
src/test/java/org/recap/service/partnerservice/ColumbiaServiceUT.java
src/test/java/org/recap/service/partnerservice/PartnerServicesUT.java
src/test/java/org/recap/service/partnerservice/PrincetonServiceUT.java

Junit Test Cases Fix

---

src/main/java/org/recap/controller/SolrIndexController.java
src/main/java/org/recap/service/accession/BulkAccessionService.java
src/main/java/org/recap/service/accession/resolver/NYPLBibDataResolver.java
src/main/java/org/recap/service/transfer/TransferService.java
src/main/java/org/recap/util/HelperUtil.java
src/main/java/org/recap/util/MatchingAlgorithmUtil.java

Removed print stack trace and logged it.

MS-229 Accession Failures - 04/12/2018.

---

src/main/java/org/recap/controller/AccessionReconcilationRestController.java

MS-239 Changes for adding customer code to the barcode reconciliation report

MS-239 Changes for adding customer code to the barcode reconciliation report

---

src/main/java/org/recap/controller/AccessionReconcilationRestController.java

MS-239 Fixed issue for empty line

MS-239 Fixed issue for empty line

---

src/main/java/org/recap/service/transfer/TransferService.java
src/main/resources/application.properties

MS-250 Transfer API will generate owningInstHoldingsId for NYPL while transferring for new bibs

MS-250 Transfer API will generate owningInstHoldingsId for NYPL while transferring for new bibs

---

src/main/java/org/recap/service/accession/AccessionValidationService.java

MS-269 To prevent accessioning a boundwith barcode with already existing owningInstitutionHoldingsId

MS-269 To prevent accessioning a boundwith barcode with already existing owningInstitutionHoldingsId

---

src/main/java/org/recap/service/accession/AccessionService.java
src/main/java/org/recap/service/accession/AccessionValidationService.java
src/test/java/org/recap/service/accession/AccessionValidationServiceUT.java

MS-269 Fix To take customer code from accession request since CUL doesnt provide customer code in XML.

MS-269 Fix To take customer code from accession request since CUL doesnt provide customer code in XML.

---

src/main/java/org/recap/model/jpa/RequestItemEntity.java

MS-288 Added a field "isGFAStatus_Sch" in ReuqestItemEntity

MS-288 Added a field "isGFAStatus_Sch" in ReuqestItemEntity

---

src/main/java/org/recap/service/accession/AccessionService.java

MS-356  - Exception occurred in SCSB Ongoing Accession Job

MS-356  - Exception occurred in SCSB Ongoing Accession Job
